export const ActionTypes = 
{
  SET_COLLECTOR: "SET_COLLECTOR",
  DELETE_COLLECTOR: "DELETE_COLLECTOR",
  SELECTED_COLLECTOR: "SELECTED_COLLECTOR",
  UNSELECTED_COLLECTOR: "UNSELECTED_COLLECTOR",
  ADD_CHARACTER: "ADD_CHARACTER",
  DELETE_CHARACTER: "DELETE_CHARACTER",
};
